export type Locale = 'pt' | 'es' | 'en'

export type LocalizedText = Record<Locale, string>

export type PartyItem = {
  id: string
  category: 'rental' | 'decoration' | 'pickup'
  audience: 'kids' | 'adults'
  name: LocalizedText
  description: LocalizedText
  image: string
}

export const items: PartyItem[] = [
  { id: 'boys-1', category: 'decoration', audience: 'kids', name: { pt: 'Capitão América', es: 'Capitán América', en: 'Captain America' }, description: { pt: 'Uma produção heroica com balões, painéis e mesa temática.', es: 'Una producción heroica con globos, paneles y mesa temática.', en: 'A heroic setup with balloons, backdrops and a themed table.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kids-boys-captain-america-5th-birthday-abraham-tuQ2zOTG4gkoh2d3QOqvnS0mYB9WLk.jpg' },
  { id: 'boys-2', category: 'decoration', audience: 'kids', name: { pt: 'Ursinho aviador', es: 'Osito aviador', en: 'Little pilot bear' }, description: { pt: 'Uma festa suave e criativa para celebrar o primeiro ano.', es: 'Una fiesta dulce y creativa para celebrar el primer año.', en: 'A soft and creative party for a first birthday.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kids-boys-dinosaur-3rd-birthday-nathan-M5397dOrF1VgT2kig7JUaHaJmq6KtA.jpg' },
  { id: 'boys-3', category: 'decoration', audience: 'kids', name: { pt: 'Baby Medeiros', es: 'Baby Medeiros', en: 'Baby Medeiros' }, description: { pt: 'Cores naturais, arco orgânico e um cenário cheio de personalidade.', es: 'Colores naturales, arco orgánico y un escenario con personalidad.', en: 'Natural colors, an organic balloon arch and a memorable backdrop.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kids-boys-farm-theme-1st-birthday-pietro-BnRBjKCejFcHIzCc9pF0CrzVYoLIpy.jpg' },
  { id: 'boys-4', category: 'decoration', audience: 'kids', name: { pt: 'Safari do Sebastian', es: 'Safari de Sebastian', en: 'Sebastian safari' }, description: { pt: 'Um cenário delicado com animais, balões e tons suaves.', es: 'Un escenario delicado con animales, globos y tonos suaves.', en: 'A soft setup with animals, balloons and gentle tones.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kids-boys-lion-safari-1st-birthday-sebastian-njO7LNte03QIi7Bz3cLw44YGFvrn7o.jpg' },
  { id: 'boys-5', category: 'decoration', audience: 'kids', name: { pt: 'Aventura do Lucca', es: 'Aventura de Lucca', en: 'Lucca adventure' }, description: { pt: 'Uma festa de avião cheia de encanto e imaginação.', es: 'Una fiesta de aviones llena de encanto e imaginación.', en: 'An airplane party full of charm and imagination.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kids-boys-airplane-1st-birthday-lucca-mkE6Lhod9DmyHVolFFtdp8qE5MBjl8.jpg' },
  { id: 'boys-6', category: 'decoration', audience: 'kids', name: { pt: 'Nuvens do Nathan', es: 'Nubes de Nathan', en: 'Nathan clouds' }, description: { pt: 'Uma composição doce para celebrar a chegada de um bebê.', es: 'Una composición dulce para celebrar la llegada de un bebé.', en: 'A sweet setup celebrating a new baby.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kids-boys-baby-shower-blue-clouds-nathan-UqEgIzZIxSnJLf1wylN7y0tLETwxT7.jpg' },
  { id: 'girls-1', category: 'decoration', audience: 'kids', name: { pt: 'Fazendinha delicada', es: 'Granjita delicada', en: 'Sweet little farm' }, description: { pt: 'Uma celebração campestre com flores, bichinhos e muito charme.', es: 'Una celebración campestre con flores, animalitos y mucho encanto.', en: 'A charming countryside celebration with flowers and farm animals.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kids-girls-farm-theme-1st-birthday-CY5SS5WxOib1C4ygEtWlv6r6kxuKKC.jpg' },
  { id: 'girls-2', category: 'decoration', audience: 'kids', name: { pt: 'Doce loja', es: 'Dulce tienda', en: 'Sweet shop' }, description: { pt: 'Uma mesa cor-de-rosa, lúdica e pronta para encantar.', es: 'Una mesa rosa, lúdica y lista para encantar.', en: 'A playful pink dessert table made to delight.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kids-girls-sweet-shop-theme-0vJ2WJD6m3vwewI4a2bNYEkLkD7imK.jpg' },
  { id: 'girls-3', category: 'decoration', audience: 'kids', name: { pt: 'Jardim de sereia', es: 'Jardín de sirena', en: 'Mermaid garden' }, description: { pt: 'Uma festa encantadora com cores suaves e detalhes do fundo do mar.', es: 'Una fiesta encantadora con colores suaves y detalles marinos.', en: 'A charming party with soft colors and under-the-sea details.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kids-girls-mermaid-theme-UHmjcj2TfP8JHs5kbBvJLsRW2Qyzju.jpg' },
  { id: 'girls-4', category: 'decoration', audience: 'kids', name: { pt: 'Festa de morango', es: 'Fiesta de fresa', en: 'Strawberry party' }, description: { pt: 'Uma comemoração doce, florida e cheia de personalidade.', es: 'Una celebración dulce, floral y llena de personalidad.', en: 'A sweet, floral celebration full of personality.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kids-girls-strawberry-1st-birthday-FH22Cx1qLD2idrsMNhWsXto4Pshhk9.jpg' },
  { id: 'girls-5', category: 'decoration', audience: 'kids', name: { pt: 'Branca de Neve', es: 'Blancanieves', en: 'Snow White' }, description: { pt: 'Uma festa clássica com doces, flores e muita magia.', es: 'Una fiesta clásica con dulces, flores y mucha magia.', en: 'A classic party with sweets, flowers and magic.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kids-girls-snow-white-2nd-birthday-sALa5htIzxg0csLADfjO69t3OyXcV8.jpg' },
  { id: 'girls-6', category: 'decoration', audience: 'kids', name: { pt: 'Aniversário rosa', es: 'Cumpleaños rosa', en: 'Pink birthday' }, description: { pt: 'Um cenário romântico ao ar livre para celebrar momentos especiais.', es: 'Un escenario romántico al aire libre para celebrar momentos especiales.', en: 'A romantic outdoor setup for special celebrations.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kids-girls-pink-birthday-9yo-REav22W2o6aPqFvwRqHIH2gfgCAqHH.jpg' },
  { id: 'adults-1', category: 'decoration', audience: 'adults', name: { pt: 'Ano novo prateado', es: 'Año nuevo plateado', en: 'Silver New Year' }, description: { pt: 'Um cenário sofisticado em prata e branco para celebrar a virada.', es: 'Un escenario sofisticado en plata y blanco para celebrar el año nuevo.', en: 'A sophisticated silver and white setup for New Year celebrations.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/adults-newyear-silver-VRdIZYmppquBAuHLAZ2nYt6gZQ2P2q.jpg' },
  { id: 'adults-2', category: 'decoration', audience: 'adults', name: { pt: 'Dourado e branco', es: 'Dorado y blanco', en: 'Gold and white' }, description: { pt: 'Uma composição elegante com balões dourados, flores e detalhes delicados.', es: 'Una composición elegante con globos dorados, flores y detalles delicados.', en: 'An elegant arrangement with gold balloons, flowers and refined details.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/adults-birthday-gold-white-Ph8hGkvjv0JpD7lHe7b6WFQbwdNiMR.jpg' },
  { id: 'adults-3', category: 'decoration', audience: 'adults', name: { pt: 'Jardim encantado', es: 'Jardín encantado', en: 'Enchanted garden' }, description: { pt: 'Uma mesa inspirada em contos de fadas, com flores vermelhas e detalhes dourados.', es: 'Una mesa inspirada en cuentos de hadas, con flores rojas y detalles dorados.', en: 'A fairytale-inspired table with red flowers and golden details.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/adults-birthday-snowwhite-red-w9eL3xgS86JsA2Cxr7WMgvKIcHaqyo.jpg' },
  { id: 'adults-4', category: 'decoration', audience: 'adults', name: { pt: 'Vermelho e dourado', es: 'Rojo y dorado', en: 'Red and gold' }, description: { pt: 'Um cenário marcante com flores, folhagens e balões em vermelho e dourado.', es: 'Un escenario impactante con flores, follaje y globos rojos y dorados.', en: 'A striking setup with flowers, greenery and red and gold balloons.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/adults-elegant-red-gold-RcWbTfzMnRPu6aqH52plgzduTen5SO.jpg' },
  { id: 'adults-5', category: 'decoration', audience: 'adults', name: { pt: 'Piquenique rosa', es: 'Picnic rosa', en: 'Pink outdoor party' }, description: { pt: 'Uma celebração ao ar livre com mesa posta, flores e tons de rosa.', es: 'Una celebración al aire libre con mesa puesta, flores y tonos rosados.', en: 'An outdoor celebration with a styled table, flowers and pink tones.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/adults-birthday-pink-outdoor-N6fdZVyRHPjCroZQO98qhpcLlpCEr9.jpg' },
  { id: 'adults-6', category: 'decoration', audience: 'adults', name: { pt: 'Pérolas e dourado', es: 'Perlas y dorado', en: 'Pearls and gold' }, description: { pt: 'Uma produção clássica em branco, pérola e dourado, com flores delicadas.', es: 'Una producción clásica en blanco, perla y dorado, con flores delicadas.', en: 'A classic white, pearl and gold setup with delicate flowers.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/adults-birthday-pearl-gold-5CPml1r5xC6ezb62iiTf0uNx5uaxZI.jpg' },
  { id: 'adults-7', category: 'decoration', audience: 'adults', name: { pt: 'Rosa e dourado', es: 'Rosa y dorado', en: 'Pink and gold' }, description: { pt: 'Uma decoração romântica com flores, balões e detalhes em rosa e dourado.', es: 'Una decoración romántica con flores, globos y detalles en rosa y dorado.', en: 'A romantic setup with flowers, balloons and pink and gold details.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/adults-birthday-pink-gold-f3QrlU8vSc3lmJJeu6U9KECd5x2Dgl.jpg' },
  { id: 'adults-8', category: 'decoration', audience: 'adults', name: { pt: 'Verde e dourado', es: 'Verde y dorado', en: 'Green and gold' }, description: { pt: 'Uma composição sofisticada com folhagens, flores brancas e balões verdes.', es: 'Una composición sofisticada con follaje, flores blancas y globos verdes.', en: 'A sophisticated arrangement with greenery, white flowers and green balloons.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/adults-birthday-green-gold-Wy7QIse6QexjEF6Tp3zkAblfO3bARl.jpg' },
]

export const translations = {
  pt: {
    nav: { portfolio: 'Portfólio', how: 'Como funciona', about: 'Sobre nós', faq: 'Dúvidas', contact: 'Contato' },
    hero: { eyebrow: 'Festas que viram memória', title: 'Pequenos detalhes. Grandes celebrações.', body: 'Decoração afetiva e peças encantadoras para deixar cada aniversário com a cara de quem você ama.', cta: 'Falar no WhatsApp', secondary: 'Ver portfólio', handmade: 'Feito à mão' },
    categories: { eyebrow: 'Do seu jeito', title: 'Escolha como celebrar', rental: 'Aluguel de Peças', rentalBody: 'Peças únicas para você criar sua composição.', decoration: 'Decoração', decorationBody: 'Montamos tudo com cuidado e personalidade.', pickup: 'Pegue e Monte', pickupBody: 'Kits práticos para celebrar no seu ritmo.' },
    portfolio: { eyebrow: 'Inspire-se', title: 'Um pouco do que fazemos', all: 'Todos', kids: 'Crianças', adults: 'Adultos', rental: 'Aluguel', decoration: 'Decoração', pickup: 'Pegue e monte', action: 'Pedir no WhatsApp', sms: 'Enviar SMS' },
    how: { eyebrow: 'Leve e gostoso', title: 'Como funciona', steps: [{ title: 'Conte seu sonho', body: 'Fale com a gente sobre a data, o tema e o que você imaginou.' }, { title: 'A gente cria', body: 'Montamos uma proposta cheia de detalhes e carinho para você.' }, { title: 'É hora de celebrar', body: 'Você recebe tudo pronto para viver um dia inesquecível.' }] },
    about: { eyebrow: 'Feito com carinho', title: 'Festas com alma, beleza e leveza.', body: 'A Donali Party é uma empresa de decoração de eventos fundada por brasileiros e localizada em Lowell, Massachusetts, com 9 anos de experiência criando celebrações únicas, elegantes e inesquecíveis. Somos especializados em decoração personalizada com balões, incluindo arcos, colunas, painéis, guirlandas e centros de mesa, além de oferecer produção completa para aniversários, chás de bebê, casamentos, aniversários de casamento e ocasiões especiais. Atendendo Lowell, MA, e cidades vizinhas, cuidamos de cada detalhe — do planejamento e design à montagem profissional no local — criando decorações personalizadas que transformam a visão de cada cliente em realidade. Como uma empresa fundada por brasileiros, a Donali Party atende com orgulho em português, inglês e espanhol, tornando o planejamento mais acolhedor e fácil para todos.', signature: 'Com carinho, equipe Donali Party' },
    faq: { eyebrow: 'Ainda ficou alguma dúvida?', title: 'Perguntas frequentes', questions: [{ q: 'Com quanto tempo devo reservar?', a: 'Recomendamos reservar com 30 dias de antecedência. Para datas especiais, fale com a gente quanto antes.' }, { q: 'Vocês atendem a minha cidade?', a: 'Atendemos a região e também enviamos kits Pegue e Monte. Consulte disponibilidade pelo WhatsApp.' }, { q: 'Posso personalizar meu pedido?', a: 'Sim! Adoramos criar propostas únicas. Conte sua ideia e vamos pensar juntos.' }] },
    contact: { eyebrow: 'Vamos criar juntos?', title: 'Sua próxima festa começa aqui.', body: 'Fale com a gente e conte como podemos deixar seu momento ainda mais especial.', cta: 'Chamar no WhatsApp', sms: 'Enviar SMS' },
    footer: 'Feito para celebrar o que realmente importa.'
  },
  es: { nav: { portfolio: 'Portafolio', how: 'Cómo funciona', about: 'Sobre nosotros', faq: 'Preguntas', contact: 'Contacto' }, hero: { eyebrow: 'Fiestas que se vuelven recuerdos', title: 'Pequeños detalles. Grandes celebraciones.', body: 'Decoración afectiva y piezas encantadoras para hacer cada cumpleaños único.', cta: 'Hablar por WhatsApp', secondary: 'Ver portafolio', handmade: 'Hecho a mano' }, categories: { eyebrow: 'A tu manera', title: 'Elige cómo celebrar', rental: 'Alquiler de piezas', rentalBody: 'Piezas únicas para crear tu composición.', decoration: 'Decoración', decorationBody: 'Montamos todo con cuidado y personalidad.', pickup: 'Recoge y monta', pickupBody: 'Kits prácticos para celebrar a tu ritmo.' }, portfolio: { eyebrow: 'Inspírate', title: 'Un poco de lo que hacemos', all: 'Todos', kids: 'Kids', adults: 'Adultos', rental: 'Alquiler', decoration: 'Decoración', pickup: 'Recoge y monta', action: 'Pedir por WhatsApp', sms: 'Enviar SMS' }, how: { eyebrow: 'Fácil y bonito', title: 'Cómo funciona', steps: [{ title: 'Cuéntanos tu sueño', body: 'Háblanos de la fecha, el tema y lo que imaginaste.' }, { title: 'Nosotros creamos', body: 'Preparamos una propuesta llena de detalles y cariño.' }, { title: 'Es hora de celebrar', body: 'Recibes todo listo para vivir un día inolvidable.' }] }, about: { eyebrow: 'Hecho con cariño', title: 'Fiestas con alma, belleza y ligereza.', body: 'Donali Party es una empresa de decoración de eventos fundada por brasileños y ubicada en Lowell, Massachusetts, con 9 años de experiencia creando celebraciones únicas, elegantes e inolvidables. Nos especializamos en decoración personalizada con globos, incluyendo arcos, columnas, fondos, guirnaldas y centros de mesa, además de ofrecer una producción completa para cumpleaños, baby showers, bodas, aniversarios y ocasiones especiales. Atendemos Lowell, MA, y las áreas cercanas, cuidando cada detalle — desde la planificación y el diseño hasta el montaje profesional en el lugar — para crear decoraciones personalizadas que hacen realidad la visión de cada cliente. Como empresa fundada por brasileños, Donali Party se enorgullece de atender en portugués, inglés y español, haciendo que el proceso de planificación sea más acogedor y sencillo para todos.', signature: 'Con cariño, equipo Donali Party' }, faq: { eyebrow: '¿Aún tienes dudas?', title: 'Preguntas frecuentes', questions: [{ q: '¿Con cuánto tiempo debo reservar?', a: 'Recomendamos reservar con 30 días de antelación.' }, { q: '¿Atienden mi ciudad?', a: 'Atendemos la región y también enviamos kits Recoge y monta.' }, { q: '¿Puedo personalizar mi pedido?', a: '¡Sí! Nos encanta crear propuestas únicas.' }] }, contact: { eyebrow: '¿Creamos juntos?', title: 'Tu próxima fiesta comienza aquí.', body: 'Háblanos y cuéntanos cómo podemos hacer tu momento aún más especial.', cta: 'Llamar por WhatsApp' }, footer: 'Hecho para celebrar lo que realmente importa.' },
  en: { nav: { portfolio: 'Portfolio', how: 'How it works', about: 'About us', faq: 'FAQ', contact: 'Contact' }, hero: { eyebrow: 'Parties that become memories', title: 'Small details. Big celebrations.', body: 'Thoughtful styling and charming pieces to make every birthday feel personal.', cta: 'Chat on WhatsApp', secondary: 'View portfolio', handmade: 'Handmade' }, categories: { eyebrow: 'Your way', title: 'Choose how to celebrate', rental: 'Piece rental', rentalBody: 'Unique pieces to create your own setup.', decoration: 'Decoration', decorationBody: 'We style everything with care and personality.', pickup: 'Pick up & style', pickupBody: 'Practical kits to celebrate at your pace.' }, portfolio: { eyebrow: 'Get inspired', title: 'A little of what we do', all: 'All', kids: 'Kids', adults: 'Adults', rental: 'Rental', decoration: 'Decoration', pickup: 'Pick up & style', action: 'Ask on WhatsApp', sms: 'Send SMS' }, how: { eyebrow: 'Easy and lovely', title: 'How it works', steps: [{ title: 'Tell us your dream', body: 'Share the date, theme and everything you imagined.' }, { title: 'We create', body: 'We prepare a thoughtful proposal made just for you.' }, { title: 'Time to celebrate', body: 'Everything arrives ready for an unforgettable day.' }] }, about: { eyebrow: 'Made with care', title: 'Parties with soul, beauty and ease.', body: 'Donali Party is a Brazilian-founded event decoration company based in Lowell, Massachusetts, with 9 years of experience creating unique, elegant, and memorable celebrations. We specialize in custom balloon decor, including balloon arches, columns, backdrops, garlands, and centerpieces, as well as complete party styling for birthdays, baby showers, weddings, anniversaries, and special occasions. Serving Lowell, MA, and surrounding areas, we take care of every detail — from planning and design to professional on-site setup — creating personalized event decorations that bring each client’s vision to life. As a Brazilian-founded business, Donali Party proudly serves clients in Portuguese, English, and Spanish, making the planning process more welcoming and seamless for everyone.', signature: 'With care, the Donali Party team' }, faq: { eyebrow: 'Still have questions?', title: 'Frequently asked questions', questions: [{ q: 'How early should I book?', a: 'We recommend booking 30 days in advance.' }, { q: 'Do you serve my city?', a: 'We serve the region and also ship Pick up & style kits.' }, { q: 'Can I customize my order?', a: 'Yes! We love creating unique proposals.' }] }, contact: { eyebrow: 'Shall we create together?', title: 'Your next party starts here.', body: 'Tell us how we can make your moment even more special.', cta: 'Chat on WhatsApp' }, footer: 'Made to celebrate what truly matters.' }
} as const

export const categoryLabel = (category: PartyItem['category'], t: (typeof translations)[Locale]) => ({ rental: t.categories.rental, decoration: t.categories.decoration, pickup: t.categories.pickup }[category])

export const whatsappUrl = (message: string) => `https://wa.me/17745285548?text=${encodeURIComponent(message)}`
