export type Locale = 'pt' | 'es' | 'en'

export type LocalizedText = Record<Locale, string>

export type PartyItem = {
  id: string
  category: 'rental' | 'decoration' | 'pickup'
  audience: 'kids' | 'adults'
  name: LocalizedText
  description: LocalizedText
  image: string
}

export const items: PartyItem[] = [
  { id: 'boys-1', category: 'decoration', audience: 'kids', name: { pt: 'Capitão América', es: 'Capitán América', en: 'Captain America' }, description: { pt: 'Uma produção heroica com balões, painéis e mesa temática.', es: 'Una producción heroica con globos, paneles y mesa temática.', en: 'A heroic setup with balloons, backdrops and a themed table.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kids-boys-captain-america-5th-birthday-abraham-tuQ2zOTG4gkoh2d3QOqvnS0mYB9WLk.jpg' },
  { id: 'boys-2', category: 'decoration', audience: 'kids', name: { pt: 'Ursinho aviador', es: 'Osito aviador', en: 'Little pilot bear' }, description: { pt: 'Uma festa suave e criativa para celebrar o primeiro ano.', es: 'Una fiesta dulce y creativa para celebrar el primer año.', en: 'A soft and creative party for a first birthday.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kids-boys-dinosaur-3rd-birthday-nathan-M5397dOrF1VgT2kig7JUaHaJmq6KtA.jpg' },
  { id: 'boys-3', category: 'decoration', audience: 'kids', name: { pt: 'Baby Medeiros', es: 'Baby Medeiros', en: 'Baby Medeiros' }, description: { pt: 'Cores naturais, arco orgânico e um cenário cheio de personalidade.', es: 'Colores naturales, arco orgánico y un escenario con personalidad.', en: 'Natural colors, an organic balloon arch and a memorable backdrop.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kids-boys-farm-theme-1st-birthday-pietro-BnRBjKCejFcHIzCc9pF0CrzVYoLIpy.jpg' },
  { id: 'boys-4', category: 'decoration', audience: 'kids', name: { pt: 'Safari do Sebastian', es: 'Safari de Sebastian', en: 'Sebastian safari' }, description: { pt: 'Um cenário delicado com animais, balões e tons suaves.', es: 'Un escenario delicado con animales, globos y tonos suaves.', en: 'A soft setup with animals, balloons and gentle tones.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kids-boys-lion-safari-1st-birthday-sebastian-njO7LNte03QIi7Bz3cLw44YGFvrn7o.jpg' },
  { id: 'boys-5', category: 'decoration', audience: 'kids', name: { pt: 'Aventura do Lucca', es: 'Aventura de Lucca', en: 'Lucca adventure' }, description: { pt: 'Uma festa de avião cheia de encanto e imaginação.', es: 'Una fiesta de aviones llena de encanto e imaginación.', en: 'An airplane party full of charm and imagination.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kids-boys-airplane-1st-birthday-lucca-mkE6Lhod9DmyHVolFFtdp8qE5MBjl8.jpg' },
  { id: 'boys-6', category: 'decoration', audience: 'kids', name: { pt: 'Nuvens do Nathan', es: 'Nubes de Nathan', en: 'Nathan clouds' }, description: { pt: 'Uma composição doce para celebrar a chegada de um bebê.', es: 'Una composición dulce para celebrar la llegada de un bebé.', en: 'A sweet setup celebrating a new baby.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kids-boys-baby-shower-blue-clouds-nathan-UqEgIzZIxSnJLf1wylN7y0tLETwxT7.jpg' },
  { id: 'girls-1', category: 'decoration', audience: 'kids', name: { pt: 'Fazendinha delicada', es: 'Granjita delicada', en: 'Sweet little farm' }, description: { pt: 'Uma celebração campestre com flores, bichinhos e muito charme.', es: 'Una celebración campestre con flores, animalitos y mucho encanto.', en: 'A charming countryside celebration with flowers and farm animals.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kids-girls-farm-theme-1st-birthday-CY5SS5WxOib1C4ygEtWlv6r6kxuKKC.jpg' },
  { id: 'girls-2', category: 'decoration', audience: 'kids', name: { pt: 'Doce loja', es: 'Dulce tienda', en: 'Sweet shop' }, description: { pt: 'Uma mesa cor-de-rosa, lúdica e pronta para encantar.', es: 'Una mesa rosa, lúdica y lista para encantar.', en: 'A playful pink dessert table made to delight.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kids-girls-sweet-shop-theme-0vJ2WJD6m3vwewI4a2bNYEkLkD7imK.jpg' },
  { id: 'girls-3', category: 'decoration', audience: 'kids', name: { pt: 'Jardim de sereia', es: 'Jardín de sirena', en: 'Mermaid garden' }, description: { pt: 'Uma festa encantadora com cores suaves e detalhes do fundo do mar.', es: 'Una fiesta encantadora con colores suaves y detalles marinos.', en: 'A charming party with soft colors and under-the-sea details.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kids-girls-mermaid-theme-UHmjcj2TfP8JHs5kbBvJLsRW2Qyzju.jpg' },
  { id: 'girls-4', category: 'decoration', audience: 'kids', name: { pt: 'Festa de morango', es: 'Fiesta de fresa', en: 'Strawberry party' }, description: { pt: 'Uma comemoração doce, florida e cheia de personalidade.', es: 'Una celebración dulce, floral y llena de personalidad.', en: 'A sweet, floral celebration full of personality.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kids-girls-strawberry-1st-birthday-FH22Cx1qLD2idrsMNhWsXto4Pshhk9.jpg' },
  { id: 'girls-5', category: 'decoration', audience: 'kids', name: { pt: 'Branca de Neve', es: 'Blancanieves', en: 'Snow White' }, description: { pt: 'Uma festa clássica com doces, flores e muita magia.', es: 'Una fiesta clásica con dulces, flores y mucha magia.', en: 'A classic party with sweets, flowers and magic.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kids-girls-snow-white-2nd-birthday-sALa5htIzxg0csLADfjO69t3OyXcV8.jpg' },
  { id: 'girls-6', category: 'decoration', audience: 'kids', name: { pt: 'Aniversário rosa', es: 'Cumpleaños rosa', en: 'Pink birthday' }, description: { pt: 'Um cenário romântico ao ar livre para celebrar momentos especiais.', es: 'Un escenario romántico al aire libre para celebrar momentos especiales.', en: 'A romantic outdoor setup for special celebrations.' }, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kids-girls-pink-birthday-9yo-REav22W2o6aPqFvwRqHIH2gfgCAqHH.jpg' },
]

export const translations = {
  pt: {
    nav: { portfolio: 'Portfólio', how: 'Como funciona', about: 'Sobre nós', faq: 'Dúvidas', contact: 'Contato' },
    hero: { eyebrow: 'Festas que viram memória', title: 'Pequenos detalhes. Grandes celebrações.', body: 'Decoração afetiva e peças encantadoras para deixar cada aniversário com a cara de quem você ama.', cta: 'Falar no WhatsApp', secondary: 'Ver portfólio', handmade: 'Feito à mão' },
    categories: { eyebrow: 'Do seu jeito', title: 'Escolha como celebrar', rental: 'Aluguel de Peças', rentalBody: 'Peças únicas para você criar sua composição.', decoration: 'Decoração', decorationBody: 'Montamos tudo com cuidado e personalidade.', pickup: 'Pegue e Monte', pickupBody: 'Kits práticos para celebrar no seu ritmo.' },
    portfolio: { eyebrow: 'Inspire-se', title: 'Um pouco do que fazemos', all: 'Todos', kids: 'Crianças', adults: 'Adultos', rental: 'Aluguel', decoration: 'Decoração', pickup: 'Pegue e monte', action: 'Pedir no WhatsApp', sms: 'Enviar SMS' },
    how: { eyebrow: 'Leve e gostoso', title: 'Como funciona', steps: [{ title: 'Conte seu sonho', body: 'Fale com a gente sobre a data, o tema e o que você imaginou.' }, { title: 'A gente cria', body: 'Montamos uma proposta cheia de detalhes e carinho para você.' }, { title: 'É hora de celebrar', body: 'Você recebe tudo pronto para viver um dia inesquecível.' }] },
    about: { eyebrow: 'Feito com carinho', title: 'Festas com alma, beleza e leveza.', body: 'A [NOME] nasceu para transformar momentos simples em histórias que ficam. Acreditamos que celebrar é cuidar dos detalhes — e que cada família merece uma festa tão especial quanto suas memórias.', signature: 'Com carinho, equipe [NOME]' },
    faq: { eyebrow: 'Ainda ficou alguma dúvida?', title: 'Perguntas frequentes', questions: [{ q: 'Com quanto tempo devo reservar?', a: 'Recomendamos reservar com 30 dias de antecedência. Para datas especiais, fale com a gente quanto antes.' }, { q: 'Vocês atendem a minha cidade?', a: 'Atendemos a região e também enviamos kits Pegue e Monte. Consulte disponibilidade pelo WhatsApp.' }, { q: 'Posso personalizar meu pedido?', a: 'Sim! Adoramos criar propostas únicas. Conte sua ideia e vamos pensar juntos.' }] },
    contact: { eyebrow: 'Vamos criar juntos?', title: 'Sua próxima festa começa aqui.', body: 'Fale com a gente e conte como podemos deixar seu momento ainda mais especial.', cta: 'Chamar no WhatsApp', sms: 'Enviar SMS' },
    footer: 'Feito para celebrar o que realmente importa.'
  },
  es: { nav: { portfolio: 'Portafolio', how: 'Cómo funciona', about: 'Sobre nosotros', faq: 'Preguntas', contact: 'Contacto' }, hero: { eyebrow: 'Fiestas que se vuelven recuerdos', title: 'Pequeños detalles. Grandes celebraciones.', body: 'Decoración afectiva y piezas encantadoras para hacer cada cumpleaños único.', cta: 'Hablar por WhatsApp', secondary: 'Ver portafolio', handmade: 'Hecho a mano' }, categories: { eyebrow: 'A tu manera', title: 'Elige cómo celebrar', rental: 'Alquiler de piezas', rentalBody: 'Piezas únicas para crear tu composición.', decoration: 'Decoración', decorationBody: 'Montamos todo con cuidado y personalidad.', pickup: 'Recoge y monta', pickupBody: 'Kits prácticos para celebrar a tu ritmo.' }, portfolio: { eyebrow: 'Inspírate', title: 'Un poco de lo que hacemos', all: 'Todos', kids: 'Kids', adults: 'Adultos', rental: 'Alquiler', decoration: 'Decoración', pickup: 'Recoge y monta', action: 'Pedir por WhatsApp', sms: 'Enviar SMS' }, how: { eyebrow: 'Fácil y bonito', title: 'Cómo funciona', steps: [{ title: 'Cuéntanos tu sueño', body: 'Háblanos de la fecha, el tema y lo que imaginaste.' }, { title: 'Nosotros creamos', body: 'Preparamos una propuesta llena de detalles y cariño.' }, { title: 'Es hora de celebrar', body: 'Recibes todo listo para vivir un día inolvidable.' }] }, about: { eyebrow: 'Hecho con cariño', title: 'Fiestas con alma, belleza y ligereza.', body: '[NOMBRE] nació para transformar momentos simples en historias que permanecen. Creemos que celebrar es cuidar los detalles.', signature: 'Con cariño, equipo [NOMBRE]' }, faq: { eyebrow: '¿Aún tienes dudas?', title: 'Preguntas frecuentes', questions: [{ q: '¿Con cuánto tiempo debo reservar?', a: 'Recomendamos reservar con 30 días de antelación.' }, { q: '¿Atienden mi ciudad?', a: 'Atendemos la región y también enviamos kits Recoge y monta.' }, { q: '¿Puedo personalizar mi pedido?', a: '¡Sí! Nos encanta crear propuestas únicas.' }] }, contact: { eyebrow: '¿Creamos juntos?', title: 'Tu próxima fiesta comienza aquí.', body: 'Háblanos y cuéntanos cómo podemos hacer tu momento aún más especial.', cta: 'Llamar por WhatsApp' }, footer: 'Hecho para celebrar lo que realmente importa.' },
  en: { nav: { portfolio: 'Portfolio', how: 'How it works', about: 'About us', faq: 'FAQ', contact: 'Contact' }, hero: { eyebrow: 'Parties that become memories', title: 'Small details. Big celebrations.', body: 'Thoughtful styling and charming pieces to make every birthday feel personal.', cta: 'Chat on WhatsApp', secondary: 'View portfolio', handmade: 'Handmade' }, categories: { eyebrow: 'Your way', title: 'Choose how to celebrate', rental: 'Piece rental', rentalBody: 'Unique pieces to create your own setup.', decoration: 'Decoration', decorationBody: 'We style everything with care and personality.', pickup: 'Pick up & style', pickupBody: 'Practical kits to celebrate at your pace.' }, portfolio: { eyebrow: 'Get inspired', title: 'A little of what we do', all: 'All', kids: 'Kids', adults: 'Adults', rental: 'Rental', decoration: 'Decoration', pickup: 'Pick up & style', action: 'Ask on WhatsApp', sms: 'Send SMS' }, how: { eyebrow: 'Easy and lovely', title: 'How it works', steps: [{ title: 'Tell us your dream', body: 'Share the date, theme and everything you imagined.' }, { title: 'We create', body: 'We prepare a thoughtful proposal made just for you.' }, { title: 'Time to celebrate', body: 'Everything arrives ready for an unforgettable day.' }] }, about: { eyebrow: 'Made with care', title: 'Parties with soul, beauty and ease.', body: '[NOME] was born to turn simple moments into stories that stay. We believe celebrating means caring about the details.', signature: 'With care, the [NOME] team' }, faq: { eyebrow: 'Still have questions?', title: 'Frequently asked questions', questions: [{ q: 'How early should I book?', a: 'We recommend booking 30 days in advance.' }, { q: 'Do you serve my city?', a: 'We serve the region and also ship Pick up & style kits.' }, { q: 'Can I customize my order?', a: 'Yes! We love creating unique proposals.' }] }, contact: { eyebrow: 'Shall we create together?', title: 'Your next party starts here.', body: 'Tell us how we can make your moment even more special.', cta: 'Chat on WhatsApp' }, footer: 'Made to celebrate what truly matters.' }
} as const

export const categoryLabel = (category: PartyItem['category'], t: (typeof translations)[Locale]) => ({ rental: t.categories.rental, decoration: t.categories.decoration, pickup: t.categories.pickup }[category])

export const whatsappUrl = (message: string) => `https://wa.me/55[NUMERO]?text=${encodeURIComponent(message)}`
